# Generated by Django 4.1.7 on 2023-05-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
