# Generated by Django 4.1.7 on 2023-05-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('ratings', models.CharField(blank=True, max_length=200, null=True)),
                ('no_of_ratings', models.CharField(blank=True, max_length=200, null=True)),
                ('discount_price', models.CharField(blank=True, max_length=200, null=True)),
                ('actual_price', models.CharField(max_length=200)),
            ],
        ),
    ]
