# Generated by Django 4.1.7 on 2023-05-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
