# Generated by Django 4.1.7 on 2023-05-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_products_image_alter_products_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
